apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: bankos-core
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 64Gi
    limits.cpu: "40"
    limits.memory: 128Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: bankos-core
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 100m
    type: Container