apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: identity
  repo: https://github.com/BankOS/bankos-infra.git
  version: 1.0.0
  releaseName: identity
  namespace: bankos-core
