apiVersion: v2
name: identity
description: Identity Service Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: bankos-microservice
    version: 1.0.0
    repository: file://../../../infrastructure/helm/charts/bankos-microservice